apiVersion: apps/v1
kind: Deployment
metadata:
  name: polaris-createservice
  labels:
    app: polaris-createservice
spec:
  replicas: 1  # Apenas um pod será criado
  selector:
    matchLabels:
      app: polaris-createservice
  template:
    metadata:
      labels:
        app: polaris-createservice
    spec:
      containers:
        - name: createservice
          image: caiovsk/createservice:latest  # Certifique-se de que a imagem está no Docker Hub
          ports:
            - containerPort: 8082  # Porta exposta no contêiner