apiVersion: v1
kind: Service
metadata:
  name: polaris-createservice
spec:
  selector:
    app: polaris-createservice
  ports:
    - protocol: TCP
      port: 8082       # Porta exposta pelo serviço
      targetPort: 8082 # Porta do contêiner
      nodePort: 30082 # Porta externa
  type: LoadBalancer
